---
- hosts: mongodb
  become: yes
  tasks:

  - name: Create List of nodes to be added into Cluster
    set_fact: nodelist={%for host in groups['mongodb']%}"{{ [host]}}"{{% endfor %}

  - debug: 
      msg: ["{{nodelist}}"]
