---
#- name: Install Import the MongoDB public GPG Key
#  shell: wget -qO - "{gpg_key}}" | sudo apt-key add -

-   name: Mongodb installation
    hosts: mongodb
    remote_user: root
    become: yes
    gather_facts: no
    vars:
        gpg_key:  https://www.mongodb.org/static/pgp/server-5.0.asc
        mongo_repo: 'deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse'
        package: 'mongodb-org'
    tasks:
        - name: Install Import the MongoDB public GPG Key
          apt_key:
            url: https://www.mongodb.org/static/pgp/server-5.0.asc
            state: present 

        - name: Add MongoDB repository
          apt_repository:
            repo: "{{mongo_repo}}"
            state: present

        - name: install mongodb
          apt: 
            pkg: "{{package}}"
            state: latest 
            update_cache: yes
          notify:
          - start mongodb

    handlers:
        - name: start mongodb
          service: 
            name: "{{package}}" 
            state: started